extends Node

var card_0_asset = load("res://assets/cards/0.png")
var card_1_asset = load("res://assets/cards/1.png")
var card_2_asset = load("res://assets/cards/2.png")
var card_3_asset = load("res://assets/cards/3.png")
var card_4_asset = load("res://assets/cards/4.png")
var card_5_asset = load("res://assets/cards/5.png")
var card_6_asset = load("res://assets/cards/6.png")
var card_7_asset = load("res://assets/cards/7.png")
var card_8_asset = load("res://assets/cards/8.png")
var card_9_asset = load("res://assets/cards/9.png")
var card_skip_asset = load("res://assets/cards/skip.png")
var card_reverse_asset = load("res://assets/cards/NoU.png")
var card_plus2_asset = load("res://assets/cards/plus2.png")
var card_plus4_asset = load("res://assets/cards/plus4.png")
var card_wild_asset = load("res://assets/cards/wild.png")
